### ISSUE TITLE
Change Energy Price to rate (EUR/kWh) instead of currency (EUR)

### ISSUE THREAD

**Issue by juanlu-sanz** [ad-ha/repsolluzygas-async#18]
Hi! love the plugin!

Since you dont have an issue template I'll use a standard one

```
AS A person that'd like to integrate their repsol data with the HA built-in energy dashboard
I WANT rates to be displayed as currency/kWh instead of just currency
SO THAT we avoid creating templates that force unit conversion
```

It could be easily achieved creating a `SensorDeviceClass` called `rate`

I haven't done a PR because I don't know if you'd like this change at all in the code.

Thank you for your time and effort and have a great day!

**Comment by ad-ha** [comment]
Great idea. I did not realize that it was not being possible to use on the Energy Dashboard.

I'm working on it. Will be releasing an update in a while
