### ISSUE TITLE
Error al añadir la integración 

### ISSUE THREAD

**Issue by jumavi** [ad-ha/repsolluzygas-async#2]
Me da este error al añadir la integración:
"No se pudo cargar el flujo de configuración: {"message":"Invalid handler specified"}"
¿Alguna solución?

**Comment by ad-ha** [comment]
Hola. Qué versión de HA estás usando?

Tienes la otra integración de Repsol Luz y Gas instalada? De ser así, la tienes que eliminar primero, borrar las configuraciones YAML y luego reiniciar HA.

Ya me dices

**Comment by jumavi** [comment]
Hola, con la última actualización me ha funcionado. Y por cierto no tenía instalada otra integración.

Gracias por solucionarlo.

**Comment by ad-ha** [comment]
Me alegro que esté funcionando.

Un saludo
