### ISSUE TITLE
Error conexion 

### ISSUE THREAD

**Issue by ElBialka** [ad-ha/repsolluzygas-async#22]
![Screenshot_20240908_130424_Home Assistant](https://github.com/user-attachments/assets/69a55402-494d-4ee0-9f1d-91bc6643f7d4)

**Comment by ad-ha** [comment]
Hi,

Without further details or logs from HA is difficult to help. Just posting a screenshot is not the best way to report an issue or ask for help.

Anyhow, I just checked the connection to the API and it's working fine on my end.

**Comment by ad-ha** [comment]
Closed without feedback
