### ISSUE TITLE
Gas readings not showing up

### ISSUE THREAD

**Issue by tomassanjuan** [ad-ha/repsolluzygas-async#25]
Hello! Gas readings and invoicing are not showing up
I don't know if this is not implemented or if help is needed to bring this to the integration.

Logs not provided for privacy. If needed, I can provide privately.

By the way, good work on this!

![image](https://github.com/user-attachments/assets/a44ac553-3892-44bc-b406-11beb0e8539d)

**Comment by tomassanjuan** [comment]
Just seen PR #24 
😂😂

**Comment by ad-ha** [comment]
Hi, @tomassanjuann 

Thanks for the update. This is with the new beta version, right?

This is already on-going with #24. 

Can you send me the full logs on alvaroduarte@smartnex.net, please?

**Comment by ad-ha** [comment]
If you have electricity contracts, please send me those logs as well. So I can cross-reference both Electricity and Gas

Cheers
