### ISSUE TITLE
Same sensor values for different contracts

### ISSUE THREAD

**Issue by ad-ha** [ad-ha/repsolluzygas-async#4]
Hello, @ad-ha 
Sí, puedo configurarlos en separado, pero los valores informados son los mismos.

_Originally posted by @edersong in https://github.com/ad-ha/repsolluzygas-async/issues/1#issuecomment-2098028784_

**Comment by edersong** [comment]
Buenos días, @ad-ha 
Ahora funciona perfectamente, gracias!

**Comment by ad-ha** [comment]
Buenos días,

Me alegro. @edersong te importaría pasarme unos pantallazos que pueda usar para la documentación?

Muchas gracias por la ayuda

**Comment by ad-ha** [comment]
Closed and solved with release 1.0.1
